<template>
  <v-col pt-4 pb-4 xl7 lg8 md10 sm11 xs11 mx-auto>
    <v-col>
      <h2 v-if="$vuetify?.breakpoint?.xs">Terms and Conditions</h2>
      <h1 v-else>Terms and Conditions</h1>
      <h3>
        <b>To continue the use of Advisor Lab,you must agree to the terms of agreement</b>
      </h3>
    </v-col>

    <v-col pt-4>
      <v-card height="450px" style="border: 1px solid #707070" class="scroll pa-4">
        <p>
          <b>Terms and Conditions of Use</b>
        </p>
        <p>
          This website (“Site”) and related services (“Services”) are provided subject to the following Terms and Conditions of
          Use (“Terms of Use”). By using this Site and Services, you agree to be bound by these Terms of Use, which govern your
          use of the Site and Services. The Site and Services are made available by PCS Retirement, LLC (“PCS”) only to users
          (referred to as “you”) who agree to these Terms of Use. If you have any questions, please contact us.
        </p>
        <p>
          Nothing contained in these Terms of Use is intended to modify or amend any other written agreement, if any, that may
          currently be in effect between you and PCS with regard to matters other than your use of the Site. PCS may periodically
          modify these Terms of Use, and any such modifications will be effective immediately upon posting. We suggest that you
          periodically check these Terms of Use for modifications. If you do not agree to these Terms of Use, do not use this
          Site. If you have any questions regarding these Terms of Use or the Site, please contact us. These Terms of Use were
          most recently revised on
          <b>11-2020.</b>. This Site is owned and operated by PCS and PCS may modify, suspend, discontinue, or restrict the use
          and availability of any portion of this Site at any time, without notice or liability. Your use of this Site may be
          monitored by PCS and used for PCS' internal business purposes and for purposes of the retirement or benefit plan for
          which you have accessed.
        </p>
        <p>
          TRANSACTIONS ARE NOT DEEMED TO BE ACCEPTED UNTIL THEY ARE REFLECTED IN THE ACCOUNT. FOR FUND INFORMATION, INCLUDING
          FEES, CHANGES AND EXPENSES, PLEASE REFER TO THE APPLICABLE PROSPECTUS.
        </p>
        <p>
          The information available on this website is from sources believed to be reliable and is not a guarantee of positions
          owned or of the value of positions shown. Positions displayed on the website may differ from the values shown in account
          statements provided by the custodian. Information obtained from this site should not be relied upon for tax or legal
          purposes.
        </p>
        <p>
          Information retrieved here is solely for informational purposes and is not intended to be an offer to buy or sell any
          security. Securities do not offer a fixed rate of return or risk. When sold, redeemed, or matured, they may be worth
          more or less than originally invested. Past performance is not indicative of future results.
        </p>
        <p>
          <b>Limited license and restrictions on use</b>
          <br />PCS grants you a limited, revocable, nonexclusive, nontransferable license to view, store, bookmark, download, and
          print the pages within this Site solely for your personal, informational, and noncommercial use or as expressly
          authorized by PCS in writing. You are responsible for obtaining and maintaining all equipment, services, and other
          materials that you need to access this Site. PCS reserves all rights not expressly granted in these Terms of Use. Except
          as otherwise stated in these Terms of Use or as expressly authorized by PCS in writing, you may not (or enable others
          to):
        </p>
        <ul>
          <li>
            <p>
              Modify, copy, screen capture, distribute, forward, transmit, post, display, perform, reproduce, publish, broadcast,
              license, create derivative works from, transfer, sell, or exploit any reports, data, information, content, products,
              services, or other materials on, generated by or obtained from this Site, whether through links or otherwise
              (collectively, "Materials");
            </p>
          </li>
          <li>
            <p>Redeliver any page, text, image, or Materials on this Site using "framing" or other technology;</p>
          </li>
          <li>
            <p>
              Engage in any conduct that could damage, disable, or overburden (i) this Site, (ii) any Materials or services
              provided through this Site, or (iii) any systems, networks, servers, or accounts related to this Site, including
              without limitation, using devices or software that provide repeated automated access to this Site, other than those
              made generally available by PCS;
            </p>
          </li>
          <li>
            <p>
              Probe, scan, or test the vulnerability of any Materials, services, systems, networks, servers, or accounts related
              to this Site or attempt to gain unauthorized access to Materials, services, systems, networks, servers, or accounts
              connected or associated with this Site through hacking, password or data mining, or any other means of circumventing
              any access-limiting, user authentication or security device of any Materials, services, systems, networks, servers,
              or accounts related to this Site;
            </p>
          </li>
          <li>
            <p>
              Modify, copy, obscure, remove, or display PCS's name, logo, trademarks, text, notices, or images without PCS's
              express written permission. To obtain such permission, you may e-mail us at sales@pcsretirement.com; or
            </p>
          </li>
          <li>
            <p>
              Include the term "PCS," or any PCS trademark or executive's name, or any variation of the foregoing, as a meta-tag,
              hidden textual element, or any other indicator that creates an impression of affiliation, sponsorship, or
              endorsement by PCS.
            </p>
          </li>
        </ul>
        <p>
          <b>Content</b><br />
          PCS does not recommend any investment advisory service or product, nor does PCS offer any advice regarding the nature,
          potential value or suitability of any particular security transaction or investment strategy. The Materials on this Site
          are for information, education, and noncommercial purposes only. Although PCS may provide data, information, and content
          from financial advisors relating to investment approaches and opportunities to buy or sell securities and/or mutual
          funds, you should not construe any such information or other content available through this Site as legal or tax advice.
          You alone will bear the sole responsibility of evaluating the merits and risks associated with the use of any Materials
          on this Site before making any decisions based on such Materials. In exchange for using such Materials, you agree not to
          hold PCS or its third-party information providers liable for any possible claim for damages arising from any decision
          you make based on the Materials made available to you through this Site. By providing access to other website, neither
          PCS nor any of its affiliates is recommending the purchase or sale of the stock issued by any company, nor are they
          endorsing services provided by any website's sponsoring organization.
        </p>
        <p>
          Certain information on this Site may contain certain forward-looking statements, which are subject to risks and
          uncertainties and speak only as of the date on which they are made. The words "believe", "expect", "anticipate",
          "optimistic", "intend", "aim", "will" or similar expressions are intended to identify forward-looking statements. You
          may not rely on these forward-looking statements, which speak only as of the date on which they are made. PCS undertakes
          no obligation to update publicly or revise any forward-looking statements. For more complete information on any
          investment, please order a free prospectus and read it carefully before you invest. All orders are at your sole risk.
          Content regarding various life events and financial, legal or tax concerns is provided for informational purposes only,
          and is not intended to be personalized advice. Please consult with your financial, investment, legal or tax advisor
          regarding the applicability of the Materials to you or your participation in the plan.
        </p>
        <p>
          To the extent that Retire On Time™ or a similar gap analysis tool is made available to you, you acknowledge that it is
          a gap analysis tool and PCS is not offering any advice regarding the nature, potential value or suitability of any
          particular security transaction or investment strategy.Neither PCS nor The Advisor Lab, LLC shall be liable to you for
          any indirect, special, consequential, incidental or punitive damages related to your use of Retire On Time™.
        </p>
        <p>
          <b>Linking conditions</b>
          <br />You may not link to this Site unless you comply with these linking conditions ("Linking Conditions"). PCS grants
          you a limited, revocable, nonexclusive right to create a hyperlink to this Site ("Link"), provided you comply at all
          times with the following conditions:
        </p>
        <ul>
          <li>
            <p>The Link must resolve to the PCS homepage (www.pcs401k.com);</p>
          </li>
          <li>
            <p>
              The text of the Link must read either "PCS Retirement, LLC” or "PCS". You may not use any PCS logo or graphic, or
              any other PCS trademark, as part of the Link without PCS’s express written permission; and
            </p>
          </li>
          <li>
            <p>
              The Link and surrounding context on the linking site must not: (a) falsely represent or misrepresent any
              relationship between the linking site and PCS, including suggestions of affiliation, endorsement, or sponsorship;
              (b) portray PCS or its affiliates, or their products or services, in a false, misleading, derogatory, or otherwise
              offensive manner; or (c) deliver the Materials in a framed environment or alter the layout, content, look, or feel
              of the Site.
            </p>
          </li>
        </ul>
        <p>
          If you have created a Link that conforms to these Linking Conditions, then you also may include one or more Links to any
          internal or subsidiary page of this Site that is located one or several levels down from the homepages (known as "deep
          links"), provided, however, that all such deep links must be in close physical proximity to the Link that conforms to
          the Linking Conditions. You may not maintain numerous or pervasive Links to this Site.
        </p>
        <p>
          <b>User content and license grant</b>
          <br />You agree that you are solely responsible for all information, data, content, text, photographs, graphics, images,
          videos, messages, comments, quotations, files, documents, and any other materials that you submit, upload, post, e-mail,
          transmit, or otherwise make available via the Site (“User Content”). By submitting, uploading, posting, e-mailing, or
          transmitting User Content to the Site, you represent and warrant that either you own all right, title, and interest in
          and to the User Content or have express permission from the owner to copy and use such User Content for all purposes
          related to the Site. PCS does not control and is not responsible for the User Content uploaded via the Site, and PCS
          neither guarantees the accuracy, quality, or appropriateness of nor endorses any User Content submitted to the Site.
        </p>
        <p>
          <b>You agree not to use the Site to:</b>
        </p>
        <ul>
          <li>
            <p>
              submit, upload, post, e-mail, transmit, or otherwise make available any User Content that is unlawful, harmful,
              threatening, abusive, menacing, harassing, tortious, defamatory, vulgar, pornographic, obscene, offensive,
              blasphemous, libelous, unlawful, invasive of another’s privacy or publicity rights, hateful, or racially,
              ethnically, or otherwise objectionable;
            </p>
          </li>
          <li>
            <p>
              submit, upload, post, e-mail, transmit, or otherwise make available any User Content that personally attacks or is
              derogatory toward PCS as an entity, PCS employees, any PCS products or services, or any PCS Materials;
            </p>
          </li>
          <li>
            <p>
              harm minors in any way, including, but not limited to, submitting, uploading, posting, e-mailing, transmitting, or
              otherwise making available content that violates child pornography laws, child sexual exploitation laws, or laws
              prohibiting the depiction of minors engaged in sexual conduct;
            </p>
          </li>
          <li>
            <p>
              impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or
              entity;
            </p>
          </li>
          <li>
            <p>
              forge headers or otherwise manipulate identifiers in order to disguise the origin of any User Content transmitted
              through the Site;
            </p>
          </li>
          <li>
            <p>
              submit, upload, post, e-mail, transmit, or otherwise make available any User Content that you do not have a right to
              make available under any law or contractual or fiduciary relationships or obligations;
            </p>
          </li>
          <li>
            <p>
              submit, upload, post, e-mail, transmit, or otherwise make available any User Content that infringes, violates, or
              misappropriates any patent, trademark, trade secret, copyright, or other intellectual property or proprietary right
              or any moral right of any party;
            </p>
          </li>
          <li>
            <p>
              submit, upload, post, e-mail, transmit, or otherwise make available any personal information or specific account
              details about yourself or any person or entity;
            </p>
          </li>
          <li>
            <p>
              submit, upload, post, e-mail, transmit, or otherwise make available any advertising, promotional materials, junk
              mail, spam, chain letters, pyramid schemes, or any other form of solicitation;
            </p>
          </li>
          <li>
            <p>
              submit, upload, post, e-mail, transmit, or otherwise make available any material that contains viruses or any other
              computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer
              software or hardware or telecommunications equipment; or
            </p>
          </li>
          <li>
            <p>
              intentionally or unintentionally violate any applicable local, state, national, or international laws, rules,
              regulations, decrees, acts, orders, directives, legislation, bills, or statutes.
            </p>
          </li>
        </ul>
        <p>
          You grant PCS and its affiliates, subsidiaries, directors, officers, employees, agents, licensors, and vendors a
          perpetual, worldwide, irrevocable, nonexclusive, fully-paid up, royalty-free, sublicensable, and transferable right and
          license to use, store, modify, adapt, translate, publish, display, broadcast, perform, disclose, distribute, sell,
          reproduce, and create derivative works from any User Content, in whole or in part, in any medium or technology
          throughout the world, including any inventions, concepts, techniques, know-how, ideas, or expressions of ideas arising
          out of or based on the User Content, for any purpose in PCS’s sole discretion, without the requirement of any permission
          from or compensation or notice, and without liability, to you or any third party. PCS shall exclusively own all right,
          title, and interest in and to any derivative works or inventions created by or on behalf of PCS that incorporate or
          otherwise make use of any User Content, without the requirement of any permission from or compensation or notice, and
          without liability, to you or any third party.
        </p>

        <p>
          Except as set forth in these Terms of Use, none of the User Content that you submit, upload, post, e-mail, or transmit
          or otherwise make available via the Site shall be subject to any confidentiality obligations by PCS and its affiliates,
          subsidiaries, directors, officers, employees, agents, licensors, and vendors. Except as may be provided by federal
          securities laws, PCS shall not be liable in any way for any User Content or for the use or disclosure of any User
          Content.
        </p>
        <p>
          You acknowledge that PCS and/or its vendors may or may not (but are not obligated to) monitor User Content, but that PCS
          shall have the right in its sole discretion to monitor, post, move, refuse, or remove any User Content, in whole or in
          part, for any reason whatsoever, without notice and without liability.
        </p>
        <p>
          <b>Copyright policy, notice, and claim information</b>
          <br />All Materials on this Site, whether separate or compiled, including, but not limited to, text, graphics, audio
          clips, logos, buttons, images, digital downloads, data compilations, software, icons, html code and xml code, as well as
          all copyright, patent, trademark, trade dress, and other rights therein, are owned or licensed by PCS and its
          third-party information providers, and are protected by United States and international intellectual property laws.
        </p>
        <p>
          Pursuant to Section 512(c)(2) of the Copyright Revision Act, as enacted through the Digital Millennium Copyright Act,
          PCS designates an agent as described below to receive notifications of claimed copyright infringement by mail:
          Christopher Egoville, PCS Retirement, LLC, 1801 Market Street, Suite 1000, Philadelphia, PA 19103.
        </p>
        <p>
          The designated copyright agent can also be reached by telephone at (267) 675-6718, by fax at (267) 675-6570, and by
          e-mail at egovillec@pcscapital.com.
        </p>
        <p>
          <b>Trademarks and patents</b>
          <br />All trademarks, service marks, and logos appearing on this Site are the exclusive property of their respective
          owners.
        </p>
        <p>
          All PCS graphics, logos, page headers, and service names are trademarks, service marks, or trade dress of PCS. PCS's
          trademarks, service marks and trade dress may not be used in connection with any product or service that is not PCS's,
          in any manner that is likely to cause confusion among customers or investors, or in any manner that disparages or
          discredits PCS. Nothing contained on this Site should be construed as granting any license or right in or to any
          trademarks, service marks, or trade dress of PCS.
        </p>
        <p>
          <b>International use</b>
          <br />Because of the global nature of the Internet, you agree to comply with all local rules with respect to your
          account and your online conduct, including all laws, rules, codes, and regulations of the country in which you reside
          and the country from which you access this Site, including without limitation, all laws, rules, codes, regulations,
          decrees, acts, orders, directives, legislation, bills, and statutes pertaining to tax, contracts, intellectual property,
          securities, e-commerce, banking, technology, computers, fraud, and privacy. In addition, you agree to comply with all
          applicable laws, rules, codes, and regulations regarding the transmission of technical data exported from the United
          States.
        </p>
        <p>
          <b>Third-party content</b><br />
          Data and other materials appearing on this Site that are provided by third parties. PCS cannot guarantee and is not
          responsible for their accuracy, timeliness, completeness, or suitability for use. PCS is not responsible for, and does
          not prepare, edit, or endorse, the content, advertising, products, or other materials on or available from any website
          owned or operated by a third party that is linked to this Site via hyperlink. The fact that PCS has provided a link to a
          third party's website does not constitute an implicit or explicit endorsement, authorization, sponsorship, or
          affiliation by PCS with respect to such website, its owners, providers, or services. You will use any such third-party
          content at your own risk and you agree that PCS is not liable for any loss or damage that you may suffer by using
          third-party websites or any content, advertising, products, or other materials in connection therewith.
        </p>
        <p>
          <b>Timeliness of content</b>
          <br />
          All content on this Site is presented only as of the date published or indicated, and may be superseded by subsequent
          market events or for other reasons. In addition, you are responsible for setting the cache settings on your browser to
          ensure you are receiving the most recent data.
        </p>
        <p><b>Information-sharing, privacy, and security</b></p>
        <p>
          <b>Information-sharing.</b> Subject to law, PCS’s agreements with plan fiduciaries and other service providers, and this
          Terms of Use, PCS will share data and information—which may include personal information about plan participants
          (including an employee who has no account but is eligible to make an elective deferral or be credited with an
          employer-provided contribution) and accountholders, a participating employer’s employees who might become eligible as a
          participant, beneficiaries, and alternate payees—with you.
        </p>
        <p>
          <b>You are the plan’s/account’s service provider.</b> For each plan or account regarding which you request information,
          you covenant that you are the plan’s or account’s service provider. If your agreement with, or service for, a plan or
          account ends, you will stop requesting information, and stop using information you obtained.
        </p>

        <p>
          <b>Only for proper purposes.</b> You covenant you will use information PCS furnished only to provide your service to the
          plan to which the information relates. (A service to the plan may include your service to an eligible employee,
          participant, beneficiary, or alternate payee regarding the plan.) You will not sell any information. You will not keep,
          use, or disclose the information other than as necessary or appropriate to provide your services to the plan or account.
          Without limiting the comprehensive effect of the preceding sentences, for personal information under California law, you
          covenant and certify you will not retain, use, or disclose personal information for any purpose other than as provided
          by this Terms of Use and applicable agreements and permitted by the California Consumer Privacy Act of 2018. You certify
          you understand these restrictions and will comply with them.
        </p>
        <p>
          You may share information with your service provider as you reasonably need to provide your services if you obtain a
          written agreement under which the service provider is bound to obligations no less than those required of you under this
          Part, and that agreement expressly provides that any person that furnished information to you is an intended third-party
          beneficiary of that agreement.
        </p>
        <p>
          <b>Compliance with laws.</b> You covenant you will obey all Federal and State privacy and security laws, including any
          law that relates to your banking, insurance, securities, or investment-adviser business (if any), as they apply to you.
          Further, you covenant you will obey the Gramm-Leach-Bliley Act title V and the California Consumer Privacy Act of 2018
          even if neither applies to you.
        </p>

        <p>
          <b>Enabling PCS’s compliance.</b> Without limiting the comprehensive effect of the above section [“Compliance with
          laws”], you covenant you will perform or provide services as needed to fulfill each valid access request, deletion
          request, and otherwise for you and PCS to comply with those laws, including the California Consumer Privacy Act of 2018.
        </p>

        <p>
          <b>Knowledge of privacy and security laws.</b> You covenant that you have and will maintain prudent knowledge of all
          Federal and State privacy and security laws described in the above “Compliance with laws” provisions, including rules,
          regulations, attorney-general opinions, and other administrative law regarding those laws.
        </p>

        <p>
          <b>Compliance procedures; supervision procedures; training.</b> You covenant your compliance procedures, supervision
          procedures, and training for your employees and agents are sufficient and prudent to meet your obligations under this
          Terms of Use, including the “Compliance with laws” and “Security controls” provisions, and applicable agreements.
        </p>

        <p>
          <b>Termination</b>
          <br />The rights granted to you herein terminate immediately upon any violation by you of these Terms of Use. PCS, in
          its sole discretion, reserves the right to temporarily or permanently terminate your access to and use of this Site at
          any time and for any reason whatsoever, without notice or liability. PCS will not be liable to you or any third party
          for any termination of your access to or use of this Site.
        </p>
        <p>
          <b>Warranty disclaimers</b>
          <br />YOU EXPRESSLY UNDERSTAND AND AGREE THAT: YOUR USE OF THIS SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS.
          TO THE FULL EXTENT PERMITTED UNDER APPLICABLE LAW, PCS AND ITS AFFILIATES, SUBSIDIARIES, DIRECTORS, OFFICERS, EMPLOYEES,
          AGENTS, LICENSORS, AND ANY THIRD-PARTY INFORMATION PROVIDERS AND VENDORS EXPRESSLY DISCLAIM ALL WARRANTIES, WHETHER
          EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, AND
          FITNESS FOR A PARTICULAR PURPOSE, AND ALL WARRANTIES REGARDING SECURITY, CURRENCY, CORRECTNESS, QUALITY, ACCURACY,
          COMPLETENESS, RELIABILITY, PERFORMANCE, TIMELINESS, OR CONTINUED AVAILABILITY, WITH RESPECT TO (I) THE SITE; (II) ANY
          MATERIALS, PRODUCTS, OR SERVICES AVAILABLE ON OR THROUGH THE SITE; (III) USE OF THE SITE, MATERIALS, PRODUCTS, OR
          SERVICES; AND (IV) THE RESULTS OF THE USE OF THE SITE, MATERIALS, PRODUCTS, OR SERVICES.
        </p>
        <p>
          FURTHER, PCS AND ITS AFFILIATES, SUBSIDIARIES, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, LICENSORS, AND ANY THIRD-PARTY
          INFORMATION PROVIDERS AND VENDORS EXPRESSLY DISCLAIM ALL WARRANTIES WITH RESPECT TO ANY DELAYS OR ERRORS IN THE
          TRANSMISSION OR DELIVERY OF ANY MATERIALS, PRODUCTS, OR SERVICES AVAILABLE THROUGH THIS SITE.
        </p>

        <p>
          EXCEPT AS PROVIDED BY LAW, NEITHER PCS NOR ITS THIRD-PARTY INFORMATION PROVIDERS AND VENDORS HAS ANY RESPONSIBILITY TO
          MAINTAIN THE MATERIALS, PRODUCTS, OR SERVICES OFFERED ON THE SITE OR TO SUPPLY CORRECTIONS, UPDATES, OR RELEASES FOR THE
          SAME.
        </p>
        <p>
          TO THE EXTENT ANY JURISDICTION DOES NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, SOME OF THE ABOVE EXCLUSIONS MAY NOT
          APPLY TO YOU. THIS WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY HAVE OTHER RIGHTS, WHICH VARY FROM JURISDICTION
          TO JURISDICTION.
        </p>
        <p>
          <b>Liability and indemnity</b>
          <br />
          ANY MATERIALS DOWNLOADED OR OTHERWISE OBTAINED THROUGH THIS SITE ARE DONE AT YOUR OWN RISK. YOU ARE SOLELY RESPONSIBLE
          FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR OTHER EQUIPMENT, OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD. NEITHER PCS
          NOR ITS AFFILIATES, SUBSIDIARIES, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, LICENSORS, OR ANY THIRD-PARTY INFORMATION
          PROVIDERS AND VENDORS WILL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR
          EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, REVENUE, INCOME, GOODWILL, USE, DATA, OR
          OTHER INTANGIBLE LOSSES, OR DAMAGES CAUSED BY THEFT, UNAUTHORIZED ACCESS, SYSTEMS FAILURE, OR COMMUNICATIONS LINE
          FAILURE, OR THE COST OF PROCURING SUBSTITUTE GOODS OR SERVICES, CAUSED BY THE USE OF OR INABILITY TO USE THE SITE,
          MATERIALS OR ANY PRODUCTS OR SERVICES PROVIDED HEREIN, OR ANY OTHER MATTER RELATING TO THIS SITE, EVEN IF PCS HAS BEEN
          ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURSIDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR
          CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU. TO THE EXTENT THAT A JURISDICTION
          DOES NOT PERMIT THE EXCLUSION OR LIMITATION OF LIABILITY AS SET FORTH HEREIN, THE LIABILITY OF PCS AND ITS AFFILIATES,
          SUBSIDIARIES, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, LICENSORS, AND ANY THIRD-PARTY INFORMATION PROVIDERS AND
        </p>
        <p>
          You agree to indemnify, defend, and hold harmless PCS, its subsidiaries and affiliates, and each of its and their
          officers, directors, employees, and agents, from and against all claims, demands, liabilities, damages, losses, or
          expenses, including attorney's fees and costs, arising out of or related to your improper access to or use of this Site,
          or any violation by you of these Terms of Use.
        </p>
        <p>
          Not in limitation of the foregoing, neither PCS nor any third party information providers or vendor shall be liable for
          any loss resulting from a cause over which such entity does not have direct control, including, without limitation, Acts
          of God, failure of electronic or mechanical equipment or communication lines, telephone or other interconnect problems,
          unauthorized access, theft, operator errors, severe weather, earthquakes and strikes or other labor problems. This
          limitation on liability includes, without limitation, the transmission of any virus or other disabling procedure or
          routine, which may infect a user's software or equipment. We cannot and do not guarantee continuous, uninterrupted or
          secure access to the Site.
        </p>

        <p>
          <b>Integration and severability</b>
          <br />If any provision of these Terms of Use is deemed unlawful, void, or unenforceable, then that provision will be
          deemed severable from these Terms of Use and will not affect the validity and enforceability of the remaining
          provisions. These Terms of Use represent the entire agreement between you and PCS relating to the subject matter herein.
        </p>
        <p>
          <b>Applicable law and venue</b><br />
          The laws of the Commonwealth of Pennsylvania, United States of America, without regard to principles of conflict of
          laws, govern these Terms of Use and any dispute that might arise between you and PCS. If you take legal action relating
          to these Terms of Use, you agree to file such action either in the Court of Common Pleas of Philadelphia County,
          Pennsylvania, or the United States District Court for the Eastern District of Pennsylvania and in no other venue, and
          you consent and submit to the personal jurisdiction of those courts for the purposes of litigating any such action.
        </p>
        <p>
          <b>Privacy</b>
          <br />Our commitment to you:
        </p>
        <p>
          At PCS, we understand that we have been entrusted with not only your hard-earned money but your personal and financial
          data as well. We recognize that your relationship with us is based on trust, and that you expect us to act responsibly
          and in your best interests. Because your personal and financial data are your private information, we hold ourselves to
          the highest standards in their safekeeping and use.
        </p>
        <p>
          This means, most importantly, that we do not sell client or prospective client information—whether it is your personal
          information or the fact that you are or may become a PCS client—TO ANYONE.
        </p>
        <p>
          Instead, we use your information to complete transactions that you request and to aid in retirement plan compliance
          services.
        </p>
        <p>
          <b>The information we collect about you</b><br />
          Personal information collected from any source may include, among other things, your name and address, Social Security
          or taxpayer identification number, date of birth, assets, income, account balances, investment activity, and accounts at
          other institutions. The information we collect about you may be transferred to or stored by PCS in the United States or
          elsewhere, as permitted by law.
        </p>
        <p>
          <b>How we handle your personal information</b><br />
          We do not sell information about current or former clients or their accounts to third parties. Nor do we share
          information about clients or prospective clients, except when needed to complete transactions, assist other service
          providers on the plan or to make you aware of related financial products and services that we offer. Here are the
          details:
        </p>
        <ul>
          <li>
            <p>
              In order to complete certain transactions or account changes that you direct, it may be necessary to provide
              identifying information to companies, individuals, or groups that are not affiliated with PCS. For example, if you
              ask to transfer assets from another financial institution to PCS, we will need to provide certain information about
              you to that company to complete the transaction.
            </p>
          </li>
          <li>
            <p>
              In certain instances, the sponsor of your retirement plan or PCS may contract with non-affiliated companies to
              perform services on behalf of the plan. Where necessary, we will disclose information we have about you to these
              third parties. In all such cases, we provide the third party with only the information necessary to carry out its
              assigned responsibilities, and only for that purpose. And we require these third parties to treat your private
              information with the same high degree of confidentiality that we do.
            </p>
          </li>
          <li>
            <p>
              Finally, we will release information about you if you direct us to do so, if we are compelled by law to do so, or in
              other legally limited circumstances (for example, to prevent fraud).
            </p>
          </li>
        </ul>
        <p>
          <b>How we protect privacy online</b>
          <br />Our concern for privacy naturally extends to those who use our websites, including the Site.
        </p>
        <ul>
          <li>
            <p>
              Our website uses some of the most secure forms of online communication available, including data encryption, Secure
              Sockets Layer (SSL) protocol, and user names and passwords. These technologies provide a high level of security and
              privacy when you access your account information, initiate online transactions, or send secure messages.
            </p>
          </li>
          <li>
            <p>
              The Site offers customized features that require our use of "HTTP cookies" and similar data files—tiny pieces of
              information that we ask your browser to store. However, we make very limited use of these data files. We don’t use
              them to pull data from your hard drive, to learn your e-mail address, or to view data in cookies or other similar
              data files created by other websites. We will not share the information in these data files or give others access to
              it—except to help us better serve your investment needs.
            </p>
          </li>
          <li>
            <p>
              When you visit the Site, we may collect, either directly or through third-party service providers, certain technical
              and navigational information, such as computer browser type, internet protocol address, pages visited, and average
              time spent on our website. This information may be used, for example, to alert you to software compatibility issues
              or to resolve technical or service problems, or it may be analyzed to improve our web design and functionality and
              our ability to serve you and your accounts.
            </p>
          </li>
        </ul>
        <p>
          <b>How we safeguard your personal information</b><br />
          Within PCS, we restrict access to information about you to those PCS employees who need to know the information in order
          to perform their jobs, such as servicing your accounts or notifying you of new products and services. To protect your
          personal information, we maintain physical, electronic, and procedural safeguards in keeping with industry standards and
          practices, and we review and adjust these safeguards regularly in response to advances in technology.
        </p>
        <p>
          <b>What you can do</b><br />
          For your protection, we strongly recommend that you do not provide your account information, user name, or password to
          anyone. If you become aware of any suspicious activity relating to your account, it is your responsibility to contact us
          immediately.
        </p>
        <p>© 2020 PCS Retirement, LLC All rights reserved</p>
      </v-card>
    </v-col>
    <v-col xs12 text-left mt-4 :class="[$vuetify?.breakpoint?.lgAndUp ? '' : 'mt-4']">
      <v-btn
        variant="outlined"
        :color="$vuetify?.theme.dark ? '' : 'accent'"
        :class="$vuetify?.breakpoint?.xs ? 'mr-0' : ''"
        @click="disagree()"
      >
        I DECLINE
      </v-btn>
      <v-btn
        :color="$vuetify?.theme.dark ? '' : 'accent'"
        :class="[$vuetify?.breakpoint?.xs ? 'mr-0' : '']"
        @click="saveLegalAgreement()"
      >
        I ACCEPT
      </v-btn>
    </v-col>
  </v-col>
</template>
<script>
export default {
  methods: {
    disagree() {
      window.location.assign('/signout')
    },
    saveLegalAgreement() {
      this.$axios.post(`api/v1/advisor/disclosureAgreement`).then(() => {
        this.$router.push('/')
      })
    }
  }
}
</script>
<style scoped>
.scroll {
  overflow-y: scroll;
}
</style>
